#!/usr/bin/env python

import knowledge_representation
import rospy
import smach_ros

from bwi_tasks.common import interruption_thread, GUI
from knowledge_representation import LongTermMemoryConduit
from smach import StateMachine, State

from bwi_tasks.common import states, control_flow, task_machine, interruption_state, interruption_manager
from bwi_kr_execution import goal_formulators, knowledge



def main():
	rospy.init_node("visit_door_list_smach")
	introspect = rospy.get_param("~introspect", False)
	
	stack = ["IDLE_TASK"]
	
	stackGUI = GUI.StackGUI(stack)
	interruptionThread = interruption_thread.InterruptionThread(introspect, stack, stackGUI)
	
	interruptionThread.start()
	stackGUI.start()

if __name__ == '__main__':
    main()
